name:                bfc
version:             1.0.0
github:              "github.com/PurpleMyst/bfc"
license:             MIT
author:              "PurpleMyst"
maintainer:          "PurpleMyst@users.noreply.github.com"
copyright:           "2019 PurpleMyst"

description: Simple brainfuck compiler

dependencies:
  - base >= 4.7 && < 5
  - llvm-hs >= 7.0 && < 8
  - llvm-hs-pure >= 7.0 && < 8
  - llvm-hs-pretty
  - text
  - containers

library:
  source-dirs: src

executables:
  bfc-exe:
    main: Main.hs
    source-dirs: src
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [bfc]
